version: "3"

services:

# databases

  db-wordpress:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  db-ilias:
    image: mysql:5.7
    command: |
     --character-set-server=utf8
     --collation-server=utf8_general_ci
     --max-allowed-packet=32M
     --default_authentication_plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=ilias

  wordpress:
    depends_on:
      - db-wordpress
    image: wordpress:latest
    volumes:
      - ./wp_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}



  phpmyadmin:
    depends_on:
      - db-wordpress
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db-wordpress
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  ilias:
    depends_on:
      - db-ilias
    image: sturai/ilias
    ports:
     - 8888:80
    links:
     - db-ilias
    environment:
      - ILIAS_AUTO_SETUP=1
      - ILIAS_DB_USER=root
      - ILIAS_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ILIAS_DB_HOST=${ILIAS_DB_HOST}
